<?php

defined( 'ABSPATH' ) || exit;

final class BSXMH_System_Tools {
    public static function register(): void {
        add_action('admin_menu',array(__CLASS__,'menu'),40);
        add_action('admin_post_bsxmh_repair_pages',array(__CLASS__,'repair_pages'));
        add_action('admin_post_bsxmh_repair_data',array(__CLASS__,'repair_data'));
        add_action('admin_post_bsxmh_finish_setup',array(__CLASS__,'finish_setup'));
        add_action('admin_notices',array(__CLASS__,'setup_notice'));
    }
    public static function menu(): void { add_submenu_page('bsxmh','Setup Wizard','Setup Wizard','bsxmh_manage_settings','bsxmh-setup',array(__CLASS__,'setup'));add_submenu_page('bsxmh','Repair Tools','Repair Tools','manage_bsxmh','bsxmh-repair',array(__CLASS__,'repair'));add_submenu_page('bsxmh','Audit Log','Audit Log','bsxmh_view_audit_log','bsxmh-audit-log',array(__CLASS__,'audit_log')); }
    public static function setup_notice():void{if(current_user_can('bsxmh_manage_settings')&&!get_option('bsxmh_setup_complete')&&($_GET['page']??'')!=='bsxmh-setup')echo '<div class="notice notice-info"><p><strong>MemberHub:</strong> Complete the <a href="'.esc_url(admin_url('admin.php?page=bsxmh-setup')).'">Setup Wizard</a> before production use.</p></div>';}
    public static function setup():void{$s=get_option('bsxmh_settings',array());echo '<div class="wrap bsxmh-wrap"><h1>MemberHub Setup Wizard</h1><div class="bsxmh-panel"><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="bsxmh_finish_setup">';wp_nonce_field('bsxmh_finish_setup');echo '<table class="form-table"><tr><th>Organization Name</th><td><input class="regular-text" required name="organization_name" value="'.esc_attr($s['organization_name']??get_bloginfo('name')).'"></td></tr><tr><th>Currency</th><td><input name="currency" value="'.esc_attr($s['currency']??'BDT').'" maxlength="3"></td></tr><tr><th>Default Monthly Fee</th><td><input type="number" step="0.01" min="0" name="default_monthly_fee" value="'.esc_attr($s['default_monthly_fee']??100).'"></td></tr><tr><th>Registration</th><td><label><input type="checkbox" name="registration_enabled" value="1" '.checked(!empty($s['registration_enabled']),true,false).'> Enable frontend registration</label></td></tr><tr><th>Admin Approval</th><td><label><input type="checkbox" name="registration_requires_approval" value="1" '.checked(!empty($s['registration_requires_approval']),true,false).'> Require approval</label></td></tr></table>';submit_button('Save & Finish Setup');echo '</form><p>Pages, roles, database tables and default funds will be verified automatically.</p></div></div>';}
    public static function finish_setup():void{if(!current_user_can('bsxmh_manage_settings'))wp_die('Not allowed.');check_admin_referer('bsxmh_finish_setup');$s=get_option('bsxmh_settings',array());$s['organization_name']=sanitize_text_field($_POST['organization_name']??'');$s['currency']=strtoupper(sanitize_key($_POST['currency']??'BDT'));$s['default_monthly_fee']=number_format(max(0,(float)($_POST['default_monthly_fee']??0)),2,'.','');$s['registration_enabled']=empty($_POST['registration_enabled'])?0:1;$s['registration_requires_approval']=empty($_POST['registration_requires_approval'])?0:1;update_option('bsxmh_settings',$s,false);BSXMH_Portal::create_pages();BSXMH_Roles::ensure_roles();BSXMH_Contributions::ensure_defaults();update_option('bsxmh_setup_complete',1,false);wp_safe_redirect(admin_url('admin.php?page=bsxmh&bsxmh_notice=setup-complete'));exit;}
    public static function repair():void{global$wpdb;$pages=get_option('bsxmh_portal_pages',array());$cron=wp_next_scheduled('bsxmh_daily_scheduled_tasks');$email_settings=get_option('bsxmh_email_settings',array());$checks=array('PHP 8.1+'=>version_compare(PHP_VERSION,'8.1','>='),'WordPress 6.5+'=>version_compare(get_bloginfo('version'),'6.5','>='),'Daily Cron'=>(bool)$cron,'Reminder Scheduler'=>empty($email_settings['scheduled_enabled'])||(bool)$cron,'REST API'=>function_exists('rest_get_server'),'HTTPS'=>is_ssl(),'Upload Writable'=>wp_is_writable(wp_upload_dir()['basedir']),'Email From Address'=>is_email($email_settings['from_email']??get_option('admin_email')));echo '<div class="wrap bsxmh-wrap"><h1>System Health & Repair</h1><div class="bsxmh-panel"><table class="widefat striped"><tbody>';foreach($checks as$n=>$ok)echo '<tr><td>'.esc_html($n).'</td><td>'.($ok?'<span style="color:green">Pass</span>':'<span style="color:#b32d2e">Needs attention</span>').'</td></tr>';echo '<tr><td>Database Version</td><td>'.esc_html((string)get_option('bsxmh_db_version')).'</td></tr><tr><td>Portal Pages</td><td>'.esc_html((string)count(array_filter($pages))).' configured</td></tr></tbody></table></div><p><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=bsxmh_repair_pages'),'bsxmh_repair_pages')).'">Repair Missing Pages</a> <a class="button button-primary" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=bsxmh_repair_data'),'bsxmh_repair_data')).'">Rebuild Receipts & Defaults</a></p></div>';}

    public static function audit_log():void{global$wpdb;$table=BSXMH_DB::table('activity_logs');$rows=$wpdb->get_results("SELECT l.*,u.display_name actor FROM $table l LEFT JOIN {$wpdb->users} u ON u.ID=l.actor_user_id ORDER BY l.id DESC LIMIT 200");echo '<div class="wrap bsxmh-wrap"><h1>Audit Log</h1><div class="bsxmh-panel"><table class="widefat striped"><thead><tr><th>Date</th><th>Actor</th><th>Action</th><th>Object</th><th>Details</th></tr></thead><tbody>';foreach($rows as$r){$details=json_decode((string)$r->details,true);echo '<tr><td>'.esc_html($r->created_at).'</td><td>'.esc_html($r->actor?:'System').'</td><td><code>'.esc_html($r->action).'</code></td><td>'.esc_html(trim((string)$r->object_type.' #'.(string)$r->object_id)).'</td><td>'.esc_html(is_array($details)?wp_json_encode($details):((string)$r->details)).'</td></tr>';}if(!$rows)echo '<tr><td colspan="5">No activity has been recorded yet.</td></tr>';echo '</tbody></table></div></div>';}

    public static function repair_pages():void{if(!current_user_can('manage_bsxmh'))wp_die('Not allowed.');check_admin_referer('bsxmh_repair_pages');BSXMH_Portal::create_pages();flush_rewrite_rules(false);wp_safe_redirect(admin_url('admin.php?page=bsxmh-repair&repaired=pages'));exit;}
    public static function repair_data():void{if(!current_user_can('manage_bsxmh'))wp_die('Not allowed.');check_admin_referer('bsxmh_repair_data');BSXMH_DB::install();BSXMH_Form_Builder::ensure_defaults();BSXMH_Contributions::ensure_defaults();BSXMH_Finance::ensure_defaults();BSXMH_Receipts::ensure_all();BSXMH_Roles::ensure_roles();wp_safe_redirect(admin_url('admin.php?page=bsxmh-repair&repaired=data'));exit;}
}
